name=input("Enter your name:")
print(name.upper())
print(name.lower())
print(name.capitalize())
print(name.title())
print(name.strip())
print(name.replace("a","@"))
print(name.find("j"))
print(name.count("a"))
print(len(name))
print(name.startswith("A"))
print(name.endswith("n"))
print(name.isalpha())
print(name.isdigit())
print(name.split(" "))
print("_".join(name))
